name: Deploy Auth (Local Runner)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to Homelab
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd /home/homelab/selfhosted/dev/backend/auth
          git reset --hard
          git pull origin dev

      - name: Rebuild and restart container
        run: |
          docker compose -f /home/homelab/selfhosted/docker-compose/auth/docker-compose.yml up -d --build
